events {
    #
}

http {
    resolver 127.0.0.11;

    upstream app_backend {
        server app:8080;
        server app2:8080;
    }

    # https server
    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        location / {
            proxy_pass http://app_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # http -> https redirect
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }
}