events {
    #
}

http {
    resolver 127.0.0.11;

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

    upstream app_backend {
        server app:8080;
        server app2:8080;
    }

    # https server
    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        # set x-frame
        add_header X-Frame-Options "DENY" always;
        # set x-content type options
        add_header X-Content-Type-Options "nosniff" always;
        # xss
        add_header X-XSS-Protection "1; mode=block" always;
        # protection accidentaly hits http instead of https
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        # refer policy
        add_header Referrer-Policy "no-referrer-when-downgrade" always;

        location / {
            proxy_pass http://app_backend;

            limit_req zone=api_limit burst=10 nodelay;
            limit_req_status 429;

            # Forward Headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;
        }
    }

    # http -> https redirect
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }
}